spring: 
  application: 
    name: console-service
    
server:
  port: 7788
  
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:6677/eureka/
    healthcheck:
      enable: true
  instance: 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2